### PR TITLE
Fix #36

### LINKED ISSUE #36: format_euro() fails for amount > 32767
`format_euro()` uses `int` for its `cent` parameter. As `int` is 16 bits in size, we end up with a negative number once we reach 32768.

### PR DESCRIPTION
**Pull request by sur5r**

### CODE REVIEW

File: src/kasse.c [hunk 1]
```diff
@@ -186,7 +186,7 @@ static signed int buy(char *name, unsigned int price) {
      * to NULL if no such credit could be found */
     credit = find_credit(nickname);
     if (credit != NULL) {
-      while ((signed int)credit->credit < ((signed int)price * einheiten)) {
+      while ((signed int)credit->credit < (price * einheiten)) {
```
Comment (stapelberg) [inline src/kasse.c]: `signed int` looks odd. Why not cast to `int32_t` instead?

Comment (sur5r) [reply src/kasse.c]: I touched as little code as possible to fix the issue. Casting to `int32_t` should be fine as well, yes.

Comment (stapelberg) [reply src/kasse.c]: Let’s do that, then? :)
